# Site settings
title: Xiaoping Zhang blog
email: xpzhang.math@whu.edu.cn
description: "Musings of a Computer Scientist."
baseurl: ""
url: "https://zxplsec.github.io"
blogurl: "http://zxplsec.github.io/blog"
#twitter_username: karpathy
github_username:  zxplsec

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
